name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - hydra-core=1.3.3
  - matplotlib=3.10.6
  - pandas=2.3.2
  - jupyterlab=4.4.7
  - pip=24.3.1
  - pip:
      - mlflow==3.4.0
      - wandb==0.22.0
