wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1710648560.64933
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.13.9
      8:
      - 5
criterion:
  desc: null
  value: mae
max_depth:
  desc: null
  value: 10
max_features:
  desc: null
  value: 0.5
max_tfidf_features:
  desc: null
  value: 5
min_samples_leaf:
  desc: null
  value: 3
min_samples_split:
  desc: null
  value: 4
n_estimators:
  desc: null
  value: 200
n_jobs:
  desc: null
  value: -1
oob_score:
  desc: null
  value: true
output_artifact:
  desc: null
  value: random_forest_export
random_seed:
  desc: null
  value: 42
rf_config:
  desc: null
  value: /home/falcon/Project-Build-an-ML-Pipeline-Starter/multirun/2024-03-16/22-07-24/1/rf_config.json
stratify_by:
  desc: null
  value: neighbourhood_group
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
