name: mlflow-af6473294b18f57ea960125076520147a7a4be59
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - attrs=23.2.0=pyh71513ae_0
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libgomp=13.2.0=h807b86a_5
  - liblapack=3.9.0=13_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.18=hf726d26_0
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - more-itertools=10.2.0=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - numpy=1.26.4=py39h474f0d3_0
  - openssl=3.2.1=hd590300_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=1.1.4=py39h9cfe711_0
  - pip=20.3.3=pyhd8ed1ab_0
  - pluggy=0.13.1=py39hf3d152e_4
  - py=1.11.0=pyh6c4a22f_0
  - pytest=6.2.2=py39hf3d152e_0
  - python=3.9.18=h0755675_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - scipy=1.5.2=py39hf3f25e7_2
  - setuptools=59.8.0=py39hf3d152e_1
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - appdirs==1.4.4
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - idna==3.6
      - pathtools==0.1.2
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyyaml==6.0.1
      - requests==2.31.0
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - wandb==0.13.9
prefix: /home/falcon/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59
