name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.13.1=pyhd8ed1ab_1
  - alsa-lib=1.2.8=h166bdaf_0
  - antlr-python-runtime=4.8=pyhd8ed1ab_3
  - anyio=3.7.1=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hd1e30aa_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=10.0.1=h3e2b116_4_cpu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.2.0=pyh71513ae_0
  - aws-c-auth=0.6.21=hd93a3ba_3
  - aws-c-cal=0.5.20=hd3b2fe5_3
  - aws-c-common=0.8.5=h166bdaf_0
  - aws-c-compression=0.2.16=hf5f93bc_0
  - aws-c-event-stream=0.2.17=h57874a7_1
  - aws-c-http=0.7.0=h96ef541_0
  - aws-c-io=0.13.12=h57ca295_1
  - aws-c-mqtt=0.7.13=h0b5698f_12
  - aws-c-s3=0.2.1=h5d7e488_4
  - aws-c-sdkutils=0.1.7=hf5f93bc_0
  - aws-checksums=0.1.14=h6027aba_0
  - aws-crt-cpp=0.18.16=h26430d7_8
  - aws-sdk-cpp=1.9.379=h56135f1_7
  - babel=2.14.0=pyhd8ed1ab_0
  - bcrypt=4.1.2=py39h9fdd4d6_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - binaryornot=0.4.4=py_1
  - bleach=6.1.0=pyhd8ed1ab_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_9
  - brotli-bin=1.0.9=h166bdaf_9
  - brotli-python=1.0.9=py39h5a03fae_9
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - chardet=5.2.0=py39hf3d152e_1
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - configparser=6.0.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py39h7633fee_0
  - cookiecutter=1.7.2=pyh9f0ad1d_0
  - cryptography=39.0.0=py39hd598818_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - curl=7.87.0=h6312ad2_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - databricks-cli=0.18.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.1=py39h3d6467e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-py=6.1.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - fftw=3.3.10=nompi_hc118613_108
  - flask=1.1.2=pyh9f0ad1d_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.50.0=py39hd1e30aa_0
  - freetype=2.12.1=h267a509_2
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - git=2.30.2=pl5320h24fefe6_1
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glib=2.80.0=hf2295e7_1
  - glib-tools=2.80.0=hde27a5a_1
  - glog=0.6.0=h6f12383_0
  - graphite2=1.3.13=h59595ed_1003
  - greenlet=3.0.3=py39h3d6467e_0
  - gst-plugins-base=1.21.3=h4243ec0_1
  - gstreamer=1.21.3=h25f0c4b_1
  - gstreamer-orc=0.4.38=hd590300_0
  - gunicorn=20.1.0=py39hf3d152e_3
  - harfbuzz=6.0.0=h8e241bc_0
  - hydra-core=1.0.6=pyhd8ed1ab_1
  - icu=70.1=h27087fc_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=5.2.0=pyha770c72_0
  - importlib_metadata=5.2.0=hd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - ipython=8.18.1=pyh707e725_3
  - ipython_genutils=0.2.0=py_1
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jack=1.9.22=h11f4161_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=2.11.3=pyhd8ed1ab_2
  - jinja2-time=0.2.0=pyhd8ed1ab_3
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.24=pyhd8ed1ab_0
  - jsonschema=4.21.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - jupyter_server=1.16.0=pyhd8ed1ab_0
  - jupyterlab=3.0.12=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.20.1=hf9c8cef_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libarrow=10.0.1=hee49ebd_4_cpu
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_9
  - libbrotlidec=1.0.9=h166bdaf_9
  - libbrotlienc=1.0.9=h166bdaf_9
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=21_linux64_openblas
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.87.0=h6312ad2_0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.10=h9b69904_4
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.80.0=hf2295e7_1
  - libgomp=13.2.0=h807b86a_5
  - libgoogle-cloud=2.5.0=h5d50b59_1
  - libgpg-error=1.48=h71f35ed_0
  - libgrpc=1.51.1=h05bd8bd_0
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=21_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=hadd5161_1
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.43=h2797004_0
  - libpq=15.1=h2baec63_3
  - libprotobuf=3.21.12=hfc55251_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libsystemd0=252=h2a991cd_0
  - libthrift=0.16.0=h491838f_2
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.4.7=h27087fc_0
  - libudev1=253=h0b41bf4_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=hd590300_5
  - llvmlite=0.42.0=py39h174d805_1
  - lz4-c=1.9.4=hcb278e6_0
  - mako=1.3.2=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=1.1.1=py39hb9d737c_4
  - matplotlib=3.6.2=py39hf3d152e_0
  - matplotlib-base=3.6.2=py39hf9fd14e_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=0.8.4=pyh1a96a4e_1006
  - mlflow=2.1.1=py39ha39b057_0
  - mpg123=1.32.4=h59595ed_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=h14678bc_0
  - mysql-libs=8.0.32=h54cf53e_0
  - nbclassic=0.5.6=pyhb4ecaf3_1
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.4.4=py39hf3d152e_0
  - nbformat=5.10.3=pyhd8ed1ab_0
  - ncurses=6.4.20240210=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.98=h1d7d5a4_0
  - numba=0.59.1=py39h615d6bd_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - omegaconf=2.0.6=py39hf3d152e_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=1.1.1w=hd590300_0
  - orc=1.8.2=hfdbbad2_2
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.2.3=py39hde0f152_0
  - pandoc=2.19.2=h32600fe_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py39h2320bf1_1
  - pip=20.3.3=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - poyo=0.5.0=py_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - protobuf=4.21.12=py39h227be39_0
  - psutil=5.9.8=py39hd1e30aa_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=16.1=h4ab2085_1
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=10.0.1=py39hacc6ce7_4_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py39hd1e30aa_3
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h5c7b992_3
  - pyqt5-sip=12.11.0=py39h227be39_3
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=h47a2c10_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.19.1=pyhd8ed1ab_0
  - python-slugify=8.0.4=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py39hd1e30aa_1
  - pyzmq=25.1.2=py39h8c080ef_0
  - qt-main=5.15.6=h18908ee_6
  - querystring_parser=1.2.4=py_0
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - referencing=0.34.0=pyhd8ed1ab_0
  - rpds-py=0.18.0=py39h9fdd4d6_0
  - s2n=1.3.31=hae46d1a_0
  - scikit-learn=1.4.1.post1=py39ha22ef79_0
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=59.8.0=py39hf3d152e_1
  - shap=0.45.0=cuda118py39hced09f5_1
  - sip=6.7.12=py39h3d6467e_0
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=1.4.49=py39hd1e30aa_1
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - terminado=0.18.1=pyh0d859eb_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - text-unidecode=1.3=pyhd8ed1ab_1
  - threadpoolctl=3.4.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py39hd1e30aa_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240316=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.43.0=pyhd8ed1ab_1
  - whichcraft=0.6.1=py_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - appdirs==1.4.4
      - docker-pycreds==0.4.0
      - htmlmin==0.1.12
      - imagehash==4.3.1
      - multimethod==1.9.1
      - networkx==3.2.1
      - numpy==1.23.5
      - pandas-profiling==3.6.2
      - pathtools==0.1.2
      - patsy==0.5.6
      - phik==0.12.4
      - pydantic==1.10.15
      - pywavelets==1.6.0
      - requests==2.28.2
      - scipy==1.9.3
      - seaborn==0.12.2
      - sentry-sdk==1.44.1
      - setproctitle==1.3.3
      - statsmodels==0.13.5
      - tangled-up-in-unicode==0.2.0
      - tqdm==4.64.1
      - typeguard==2.13.3
      - urllib3==1.26.18
      - visions==0.7.5
      - wandb==0.13.9
prefix: /home/pglad/miniconda3/envs/nyc_airbnb_dev
