name: mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.13.1=pyhd8ed1ab_1
  - aws-c-auth=0.7.8=h5c941e0_1
  - aws-c-cal=0.6.9=h5d48c4d_2
  - aws-c-common=0.9.10=hd590300_0
  - aws-c-compression=0.2.17=h7f92143_7
  - aws-c-event-stream=0.3.2=h0bcb0bb_8
  - aws-c-http=0.7.14=hd268abd_3
  - aws-c-io=0.13.36=hb3b01f7_3
  - aws-c-mqtt=0.9.10=h35285c7_2
  - aws-c-s3=0.4.1=h0448019_2
  - aws-c-sdkutils=0.1.12=h7f92143_6
  - aws-checksums=0.1.17=h7f92143_6
  - aws-crt-cpp=0.24.8=h5e14d71_2
  - aws-sdk-cpp=1.11.210=ha5d3ae3_2
  - bcrypt=4.1.2=py39h9fdd4d6_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - configparser=6.0.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py39h7633fee_0
  - cryptography=42.0.5=py39hd4f0224_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - databricks-cli=0.18.0=pyhd8ed1ab_0
  - dbus=1.13.18=hb2f20db_0
  - docker-py=6.1.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - flask=2.3.3=pyhd8ed1ab_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonttools=4.49.0=py39hd1e30aa_0
  - freetype=2.12.1=h267a509_2
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.42=pyhd8ed1ab_0
  - glib=2.80.0=hf2295e7_0
  - glib-tools=2.80.0=hde27a5a_0
  - glog=0.6.0=h6f12383_0
  - greenlet=3.0.3=py39h3d6467e_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gunicorn=20.1.0=py39hf3d152e_3
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=5.2.0=pyha770c72_0
  - importlib_resources=6.3.0=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.20.1=h81ceb04_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=3.0=h9c3ff4c_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarrow=10.0.1=he8e060f_57_cpu
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=21_linux64_openblas
  - libclang=14.0.6=default_h7634d5b_1
  - libclang13=14.0.6=default_h9986a30_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h36d4200_3
  - libcurl=8.5.0=h251f7ec_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.80.0=hf2295e7_0
  - libgomp=13.2.0=h807b86a_5
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgrpc=1.59.3=hd6c4280_0
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=21_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libpq=12.17=hdbd6064_0
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.09.01=h7a70373_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.3.0=h0fcbabc_4
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.6.0=hd429924_1
  - libxml2=2.12.5=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - llvmlite=0.42.0=py39h174d805_1
  - lz4-c=1.9.4=hcb278e6_0
  - mako=1.3.2=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - matplotlib=3.6.2=py39hf3d152e_0
  - matplotlib-base=3.6.2=py39hf9fd14e_0
  - mlflow=2.1.1=py39ha39b057_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql=5.7.20=hf484d3e_1001
  - ncurses=6.4=h59595ed_2
  - numba=0.59.0=py39h615d6bd_1
  - numpy=1.26.4=py39h474f0d3_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - olefile=0.47=pyhd8ed1ab_0
  - openjpeg=2.5.0=h7d73246_0
  - openssl=3.2.1=hd590300_0
  - orc=1.9.2=h4b38347_0
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.1.4=py39h9cfe711_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pillow=8.1.2=py39hf95b381_1
  - pip=20.3.3=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.0=pyhd8ed1ab_0
  - protobuf=4.24.4=py39h60f6b12_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyarrow=10.0.1=py39h1cb0ea7_57_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py39hd1e30aa_3
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.4=py39h5a03fae_0
  - pyqt5-sip=12.9.0=py39h5a03fae_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.18=h0755675_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py39hd1e30aa_1
  - qt-main=5.15.2=h53bd1ea_10
  - querystring_parser=1.2.4=py_0
  - rdma-core=50.0=hd3aeb46_1
  - re2=2023.09.01=h7f4b329_1
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - s2n=1.4.1=h06160fa_0
  - scikit-learn=0.24.1=py39h4dfa638_0
  - scipy=1.12.0=py39h474f0d3_2
  - setuptools=59.8.0=py39hf3d152e_1
  - shap=0.45.0=cpu_py39h1e20468_0
  - sip=6.5.1=py39he80948d_2
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sqlalchemy=1.4.49=py39hd1e30aa_1
  - sqlite=3.45.2=h2c6b66d_0
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - threadpoolctl=3.3.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.4=py39hd1e30aa_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=h11edf95_7
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xkeyboard-config=2.41=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - appdirs==1.4.4
      - docker-pycreds==0.4.0
      - pathtools==0.1.2
      - psutil==5.9.8
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - wandb==0.13.9
prefix: /home/falcon/miniconda3/envs/mlflow-d6c04384fb9356865b6d231fc3cbd1b1b9b4863e
