name: mlflow-19707c3818ce7e70ccc2f8b703046ae5d9c85174
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.7.4=hbcca054_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgomp=14.1.0=h77fa898_0
  - liblapack=3.9.0=22_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=h59595ed_0
  - numpy=1.26.4=py39h474f0d3_0
  - openssl=3.3.1=h4ab18f5_1
  - pandas=1.2.3=py39hde0f152_0
  - pip=20.3.3=pyhd8ed1ab_0
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - setuptools=59.8.0=py39hf3d152e_1
  - six=1.16.0=pyh6c4a22f_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024a=h0c530f3_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - appdirs==1.4.4
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - docker-pycreds==0.4.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - idna==3.7
      - pathtools==0.1.2
      - protobuf==4.25.3
      - psutil==6.0.0
      - pyyaml==6.0.1
      - requests==2.32.3
      - sentry-sdk==2.10.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - wandb==0.13.9
prefix: /home/sloya7/miniconda3/envs/mlflow-19707c3818ce7e70ccc2f8b703046ae5d9c85174
