name: mlflow-c783dc507c6bedc1b58f0a87f952c3c2d2f33013
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.13.2=pyhd8ed1ab_0
  - aws-c-auth=0.7.8=h5c941e0_1
  - aws-c-cal=0.6.9=h5d48c4d_2
  - aws-c-common=0.9.10=hd590300_0
  - aws-c-compression=0.2.17=h7f92143_7
  - aws-c-event-stream=0.3.2=h0bcb0bb_8
  - aws-c-http=0.7.14=hd268abd_3
  - aws-c-io=0.13.36=hb3b01f7_3
  - aws-c-mqtt=0.9.10=h35285c7_2
  - aws-c-s3=0.4.1=h0448019_2
  - aws-c-sdkutils=0.1.12=h7f92143_6
  - aws-checksums=0.1.17=h7f92143_6
  - aws-crt-cpp=0.24.8=h5e14d71_2
  - aws-sdk-cpp=1.11.210=ha5d3ae3_2
  - bcrypt=4.1.3=py39ha68c5e3_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.32.2=h4bc722e_0
  - ca-certificates=2024.7.4=hbcca054_0
  - certifi=2024.7.4=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.2.1=py39h7633fee_0
  - cryptography=42.0.8=py39h8169da8_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - docker-py=6.1.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - flask=2.3.3=pyhd8ed1ab_0
  - fonttools=4.53.1=py39hcd6043d_0
  - freetype=2.12.1=h267a509_2
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - glog=0.6.0=h6f12383_0
  - greenlet=3.0.3=py39h3d6467e_0
  - gunicorn=20.1.0=py39hf3d152e_3
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=5.2.0=pyha770c72_0
  - importlib-resources=6.4.0=pyhd8ed1ab_0
  - importlib_resources=6.4.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarrow=10.0.1=he8e060f_57_cpu
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=14.1.0=h77fa898_0
  - libgfortran-ng=14.1.0=h69a702a_0
  - libgfortran5=14.1.0=hc5f4f2c_0
  - libgomp=14.1.0=h77fa898_0
  - libgoogle-cloud=2.12.0=h5206363_4
  - libgrpc=1.59.3=hd6c4280_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=22_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.24.4=hf27288f_0
  - libre2-11=2023.09.01=h7a70373_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=14.1.0=hc0a3c3a_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=h1dd3fc0_3
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.16=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - llvmlite=0.43.0=py39h81bab63_0
  - lz4-c=1.9.4=hcb278e6_0
  - mako=1.3.5=pyhd8ed1ab_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - matplotlib-base=3.9.1=py39hd75cb13_0
  - mlflow=2.1.1=py39ha39b057_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h59595ed_0
  - numba=0.60.0=py39h0320e7d_0
  - numpy=1.26.4=py39h474f0d3_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.3.1=h4bc722e_2
  - orc=1.9.2=h4b38347_0
  - packaging=22.0=pyhd8ed1ab_0
  - pandas=1.1.4=py39h9cfe711_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - pillow=10.4.0=py39h16a7006_0
  - pip=20.3.3=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.1=pyhd8ed1ab_0
  - protobuf=4.24.4=py39h60f6b12_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyarrow=10.0.1=py39h1cb0ea7_57_cpu
  - pycparser=2.22=pyhd8ed1ab_0
  - pynacl=1.5.0=py39hd1e30aa_3
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py39hd1e30aa_1
  - qhull=2020.2=h434a139_5
  - querystring_parser=1.2.4=py_0
  - rdma-core=52.0=he02047a_0
  - re2=2023.09.01=h7f4b329_1
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - s2n=1.4.1=h06160fa_0
  - scikit-learn=0.24.1=py39h4dfa638_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=59.8.0=py39hf3d152e_1
  - shap=0.45.1=cpu_py39h853acf6_0
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlalchemy=1.4.49=py39hd1e30aa_1
  - sqlparse=0.5.1=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.4=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=ha691c75_8
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.19.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py39h623c9ba_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - appdirs==1.4.4
      - databricks-cli==0.18.0
      - docker-pycreds==0.4.0
      - oauthlib==3.2.2
      - pathtools==0.1.2
      - psutil==6.0.0
      - pyjwt==2.8.0
      - sentry-sdk==2.10.0
      - setproctitle==1.3.3
      - tabulate==0.9.0
      - wandb==0.13.9
      - wandb-utils==0.1
prefix: /home/sloya7/miniconda3/envs/mlflow-c783dc507c6bedc1b58f0a87f952c3c2d2f33013
