wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.18
    start_time: 1710646131.856023
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.9.18
      5: 0.13.9
      8:
      - 5
input_artifact:
  desc: null
  value: sample.csv:latest
max_price:
  desc: null
  value: 350.0
min_price:
  desc: null
  value: 10.0
output_artifact:
  desc: null
  value: clean_sample.csv
output_description:
  desc: null
  value: Data with outliers and null values removed
output_type:
  desc: null
  value: clean_sample
