wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.19
    start_time: 1712258476.466748
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 5
      - 23
      - 24
      4: 3.9.19
      5: 0.13.9
      8:
      - 5
